version: '3.7'

services:
  api:
    build:
      context: ./backend
      dockerfile: dockerfile
      target: base
    restart: always
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/assets:/home/node/app/assets
      - ./backend/nodemon.json:/home/node/app/nodemon.json
      - ./static_site/static:/home/node/app/uploads
    command: npm run dev
  nginx:
      image: nginx:latest
      ports:
          - "1313:8080"
      volumes:
          - ./backend/nginx/lb.dev.conf:/etc/nginx/conf.d/lb.conf
      depends_on:
          - api
